openapi: 3.0.0
info:
  title: Magical Tsutsun List
  description: API de librería de animes y mangas.
  version: 1.0.0
paths:
  /magicaltsutsunlist/v1/seasonal-anime:
    get:
      summary: Se obtienen los animes de la temporada actual.
      description: Se devuelve una lista de los animes de la temporada actual con información relevante como título, imagen y géneros.
      tags:
        - Animes
      responses:
        200:
          description: Respuesta exitosa con los animes de temporada.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                      description: El título del anime.
                    image_url:
                      type: string
                      description: La URL de la imagen del anime.
                      format: uri
                    genres:
                      type: array
                      items:
                        type: string
                      description: Lista de géneros asociados al anime.
        500:
          description: Error al obtener los animes de temporada.
          content:
            text/plain:
              schema:
                type: string
                example: Error al obtener los animes de temporada.

  /magicaltsutsunlist/v1/sync-and-insert-anime:
    get:
      summary: Se sincronizan los datos de anime y se insertan en la base de datos de MySQL.
      description: Se conecta a la base de datos de MySQL, se sincroniza y después se insertan los datos de los animes.
      tags:
        - Animes
      responses:
        200:
          description: Animes sincronizados e insertados con éxito.
          content:
            text/plain:
              schema:
                type: string
                example: 'Datos sincronizados e insertados.'
        500:
          description: Error al sincronizar e insertar los animes.
          content:
            text/plain:
              schema:
                type: string
                example: 'Error al sincronizar e insertar los animes.'

  /magicaltsutsunlist/v1/collections/animes:
    get:
      summary: Se obtiene la información de todos los animes almacenados en la base de datos de MongoDB.
      tags:
        - Animes
      responses:
        200:
          description: Listado de todos los animes.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      example: "67bb9f278732e96514be324e"
                    title:
                      type: string
                      example: "Bouken Ou Beet"
                    synopsis:
                      type: string
                      example: "It is the dark century and the people are suffering under the rule of the devil, Vandel, who is able to manipulate monsters..."
                    genres:
                      type: array
                      items:
                        type: string
                      example: [ "Action", "Adventure", "Fantasy" ]
                    image:
                      type: string
                      example: "https://cdn.myanimelist.net/images/anime/7/21569l.jpg"
        500:
          description: Error interno del servidor.
          content:
            text/plain:
              schema:
                type: string
                example: 'Internal Server Error'

  /magicaltsutsunlist/v1/user/anime-status/add:
    post:
      summary: Se añade o actualiza el estado de un anime en la lista personal del usuario.
      description: Esta ruta permite agregar o actualizar el estado de un anime en la lista personal de un usuario. Si el estado es "Drop", el anime será eliminado de la lista.
      tags:
        - Animes
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                animeData:
                  type: object
                  description: Datos del anime que se va a añadir o actualizar en la lista.
                  example: { "_id": "67cc1f4b7350eac8e9842104", "title": "Ojamajo Doremi" }
                status:
                  type: string
                  description: El estado del anime en la lista del usuario ("Watching", "Completed", "Drop"...).
                  example: "Watching"
      responses:
        201:
          description: Anime añadido/actualizado con éxito.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Anime successfully added/updated."
                  anime:
                    type: object
                    description: Datos del anime actualizado.
                    example: { "_id": "67cc1f4b7350eac8e9842104", "title": "Ojamajo Doremi", "status": "Completed"}
        500:
          description: Error al añadir anime.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Error adding anime."
                  error:
                    type: object
                    description: Detalles del error.
                    example: { "message": "Error adding anime.", "code": "500" }

  /magicaltsutsunlist/v1/user/anime-status/list:
    get:
      summary: Se obtiene la lista personal de animes de un usuario.
      description: Esta ruta devuelve la lista de animes del usuario autenticado.
      tags:
        - Animes
      security:
        - BearerAuth: []
      responses:
        200:
          description: Lista de animes del usuario.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    animeId:
                      type: string
                      description: ID del anime.
                      example: "67cc1f4b7350eac8e9842104"
                    title:
                      type: string
                      description: Título del anime.
                      example: "Ojamajo Doremi"
                    synopsis:
                      type: string
                      description: Sinopsis del anime.
                      example: "Harukaze Doremi considers herself to be the unluckiest girl in the world..."
                    image:
                      type: string
                      description: URL de la imagen del anime o ruta relativa de la imagen local.
                      example: "/uploads/animes/anime1.jpg"
                    genres:
                      type: array
                      description: Género o géneros del anime.
                      items:
                        type: string
                      example: [ "Comedy", "Fantasy" ]
                    status:
                      type: string
                      description: Estado del anime en la lista.
                      example: "Watching"
        500:
          description: Error al obtener la lista.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Error fetching the list."
                  error:
                    type: object
                    description: Detalles del error.
                    example: { "message": "Internal server error.", "code": "500" }

  /magicaltsutsunlist/v1/user/anime-status/{animeId}:
    delete:
      summary: Eliminar un anime de la lista personal del usuario.
      description: Esta ruta elimina un anime de la lista personal del usuario utilizando el ID del anime.
      tags:
        - Animes
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: animeId
          required: true
          description: ID del anime que se va a eliminar de la lista.
          schema:
            type: string
            example: "67bb9f278732e96514be3257"
      responses:
        200:
          description: Anime eliminado con éxito.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Anime successfully deleted."
        404:
          description: Anime no encontrado en la lista.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Anime not found in the list."
        500:
          description: Error al eliminar anime.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Error deleting anime."
                  error:
                    type: object
                    description: Detalles del error.
                    example: { "message": "Internal server error", "code": "500" }
